/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProblemListRouteImport } from './routes/problem-list'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ProblemsRouteRouteImport } from './routes/problems/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VizIdRouteImport } from './routes/viz/$id'
import { Route as ProblemsValidateBstRouteImport } from './routes/problems/validate-bst'
import { Route as ProblemsUndergroundSystemRouteImport } from './routes/problems/underground-system'
import { Route as ProblemsTopKFrequentWordsRouteImport } from './routes/problems/top-k-frequent-words'
import { Route as ProblemsThreeSumRouteImport } from './routes/problems/three-sum'
import { Route as ProblemsSubarraySumKRouteImport } from './routes/problems/subarray-sum-k'
import { Route as ProblemsSingleElementSortedRouteImport } from './routes/problems/single-element-sorted'
import { Route as ProblemsShortestPathBinaryMatrixRouteImport } from './routes/problems/shortest-path-binary-matrix'
import { Route as ProblemsRottingOrangesRouteImport } from './routes/problems/rotting-oranges'
import { Route as ProblemsRotateImageRouteImport } from './routes/problems/rotate-image'
import { Route as ProblemsReverseIntegerRouteImport } from './routes/problems/reverse-integer'
import { Route as ProblemsRemoveDuplicatesIiRouteImport } from './routes/problems/remove-duplicates-ii'
import { Route as ProblemsRandomizedSetRouteImport } from './routes/problems/randomized-set'
import { Route as ProblemsOrderedStreamRouteImport } from './routes/problems/ordered-stream'
import { Route as ProblemsMergeSortedArrayRouteImport } from './routes/problems/merge-sorted-array'
import { Route as ProblemsMagicDictionaryRouteImport } from './routes/problems/magic-dictionary'
import { Route as ProblemsLruCacheRouteImport } from './routes/problems/lru-cache'
import { Route as ProblemsLongestCommonPrefixRouteImport } from './routes/problems/longest-common-prefix'
import { Route as ProblemsFruitIntoBasketsRouteImport } from './routes/problems/fruit-into-baskets'
import { Route as ProblemsFlattenMultilevelListRouteImport } from './routes/problems/flatten-multilevel-list'
import { Route as ProblemsFizzBuzzRouteImport } from './routes/problems/fizz-buzz'
import { Route as ProblemsDecodeStringRouteImport } from './routes/problems/decode-string'
import { Route as ProblemsContainerWaterRouteImport } from './routes/problems/container-water'
import { Route as ProblemsBrowserHistoryRouteImport } from './routes/problems/browser-history'
import { Route as ProblemsBasicCalculatorIiRouteImport } from './routes/problems/basic-calculator-ii'
import { Route as ProblemsAddTwoNumbersRouteImport } from './routes/problems/add-two-numbers'
import { Route as ProblemsAddBinaryRouteImport } from './routes/problems/add-binary'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as AdminProblemsNewRouteImport } from './routes/admin/problems/new'
import { Route as AdminProblemsSlugRouteImport } from './routes/admin/problems/$slug'

const ProblemListRoute = ProblemListRouteImport.update({
  id: '/problem-list',
  path: '/problem-list',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRouteRoute = ProblemsRouteRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VizIdRoute = VizIdRouteImport.update({
  id: '/viz/$id',
  path: '/viz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsValidateBstRoute = ProblemsValidateBstRouteImport.update({
  id: '/validate-bst',
  path: '/validate-bst',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsUndergroundSystemRoute =
  ProblemsUndergroundSystemRouteImport.update({
    id: '/underground-system',
    path: '/underground-system',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsTopKFrequentWordsRoute =
  ProblemsTopKFrequentWordsRouteImport.update({
    id: '/top-k-frequent-words',
    path: '/top-k-frequent-words',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsThreeSumRoute = ProblemsThreeSumRouteImport.update({
  id: '/three-sum',
  path: '/three-sum',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsSubarraySumKRoute = ProblemsSubarraySumKRouteImport.update({
  id: '/subarray-sum-k',
  path: '/subarray-sum-k',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsSingleElementSortedRoute =
  ProblemsSingleElementSortedRouteImport.update({
    id: '/single-element-sorted',
    path: '/single-element-sorted',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsShortestPathBinaryMatrixRoute =
  ProblemsShortestPathBinaryMatrixRouteImport.update({
    id: '/shortest-path-binary-matrix',
    path: '/shortest-path-binary-matrix',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsRottingOrangesRoute = ProblemsRottingOrangesRouteImport.update({
  id: '/rotting-oranges',
  path: '/rotting-oranges',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsRotateImageRoute = ProblemsRotateImageRouteImport.update({
  id: '/rotate-image',
  path: '/rotate-image',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsReverseIntegerRoute = ProblemsReverseIntegerRouteImport.update({
  id: '/reverse-integer',
  path: '/reverse-integer',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsRemoveDuplicatesIiRoute =
  ProblemsRemoveDuplicatesIiRouteImport.update({
    id: '/remove-duplicates-ii',
    path: '/remove-duplicates-ii',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsRandomizedSetRoute = ProblemsRandomizedSetRouteImport.update({
  id: '/randomized-set',
  path: '/randomized-set',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsOrderedStreamRoute = ProblemsOrderedStreamRouteImport.update({
  id: '/ordered-stream',
  path: '/ordered-stream',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsMergeSortedArrayRoute =
  ProblemsMergeSortedArrayRouteImport.update({
    id: '/merge-sorted-array',
    path: '/merge-sorted-array',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsMagicDictionaryRoute = ProblemsMagicDictionaryRouteImport.update({
  id: '/magic-dictionary',
  path: '/magic-dictionary',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsLruCacheRoute = ProblemsLruCacheRouteImport.update({
  id: '/lru-cache',
  path: '/lru-cache',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsLongestCommonPrefixRoute =
  ProblemsLongestCommonPrefixRouteImport.update({
    id: '/longest-common-prefix',
    path: '/longest-common-prefix',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsFruitIntoBasketsRoute =
  ProblemsFruitIntoBasketsRouteImport.update({
    id: '/fruit-into-baskets',
    path: '/fruit-into-baskets',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsFlattenMultilevelListRoute =
  ProblemsFlattenMultilevelListRouteImport.update({
    id: '/flatten-multilevel-list',
    path: '/flatten-multilevel-list',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsFizzBuzzRoute = ProblemsFizzBuzzRouteImport.update({
  id: '/fizz-buzz',
  path: '/fizz-buzz',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsDecodeStringRoute = ProblemsDecodeStringRouteImport.update({
  id: '/decode-string',
  path: '/decode-string',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsContainerWaterRoute = ProblemsContainerWaterRouteImport.update({
  id: '/container-water',
  path: '/container-water',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsBrowserHistoryRoute = ProblemsBrowserHistoryRouteImport.update({
  id: '/browser-history',
  path: '/browser-history',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsBasicCalculatorIiRoute =
  ProblemsBasicCalculatorIiRouteImport.update({
    id: '/basic-calculator-ii',
    path: '/basic-calculator-ii',
    getParentRoute: () => ProblemsRouteRoute,
  } as any)
const ProblemsAddTwoNumbersRoute = ProblemsAddTwoNumbersRouteImport.update({
  id: '/add-two-numbers',
  path: '/add-two-numbers',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const ProblemsAddBinaryRoute = ProblemsAddBinaryRouteImport.update({
  id: '/add-binary',
  path: '/add-binary',
  getParentRoute: () => ProblemsRouteRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsNewRoute = AdminProblemsNewRouteImport.update({
  id: '/admin/problems/new',
  path: '/admin/problems/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsSlugRoute = AdminProblemsSlugRouteImport.update({
  id: '/admin/problems/$slug',
  path: '/admin/problems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/problem-list': typeof ProblemListRoute
  '/p/$slug': typeof PSlugRoute
  '/problems/add-binary': typeof ProblemsAddBinaryRoute
  '/problems/add-two-numbers': typeof ProblemsAddTwoNumbersRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/browser-history': typeof ProblemsBrowserHistoryRoute
  '/problems/container-water': typeof ProblemsContainerWaterRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/fizz-buzz': typeof ProblemsFizzBuzzRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/fruit-into-baskets': typeof ProblemsFruitIntoBasketsRoute
  '/problems/longest-common-prefix': typeof ProblemsLongestCommonPrefixRoute
  '/problems/lru-cache': typeof ProblemsLruCacheRoute
  '/problems/magic-dictionary': typeof ProblemsMagicDictionaryRoute
  '/problems/merge-sorted-array': typeof ProblemsMergeSortedArrayRoute
  '/problems/ordered-stream': typeof ProblemsOrderedStreamRoute
  '/problems/randomized-set': typeof ProblemsRandomizedSetRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/rotting-oranges': typeof ProblemsRottingOrangesRoute
  '/problems/shortest-path-binary-matrix': typeof ProblemsShortestPathBinaryMatrixRoute
  '/problems/single-element-sorted': typeof ProblemsSingleElementSortedRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/top-k-frequent-words': typeof ProblemsTopKFrequentWordsRoute
  '/problems/underground-system': typeof ProblemsUndergroundSystemRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
  '/viz/$id': typeof VizIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/problems/$slug': typeof AdminProblemsSlugRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/problem-list': typeof ProblemListRoute
  '/p/$slug': typeof PSlugRoute
  '/problems/add-binary': typeof ProblemsAddBinaryRoute
  '/problems/add-two-numbers': typeof ProblemsAddTwoNumbersRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/browser-history': typeof ProblemsBrowserHistoryRoute
  '/problems/container-water': typeof ProblemsContainerWaterRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/fizz-buzz': typeof ProblemsFizzBuzzRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/fruit-into-baskets': typeof ProblemsFruitIntoBasketsRoute
  '/problems/longest-common-prefix': typeof ProblemsLongestCommonPrefixRoute
  '/problems/lru-cache': typeof ProblemsLruCacheRoute
  '/problems/magic-dictionary': typeof ProblemsMagicDictionaryRoute
  '/problems/merge-sorted-array': typeof ProblemsMergeSortedArrayRoute
  '/problems/ordered-stream': typeof ProblemsOrderedStreamRoute
  '/problems/randomized-set': typeof ProblemsRandomizedSetRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/rotting-oranges': typeof ProblemsRottingOrangesRoute
  '/problems/shortest-path-binary-matrix': typeof ProblemsShortestPathBinaryMatrixRoute
  '/problems/single-element-sorted': typeof ProblemsSingleElementSortedRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/top-k-frequent-words': typeof ProblemsTopKFrequentWordsRoute
  '/problems/underground-system': typeof ProblemsUndergroundSystemRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
  '/viz/$id': typeof VizIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/problems/$slug': typeof AdminProblemsSlugRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problems': typeof ProblemsRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/gallery': typeof GalleryRoute
  '/problem-list': typeof ProblemListRoute
  '/p/$slug': typeof PSlugRoute
  '/problems/add-binary': typeof ProblemsAddBinaryRoute
  '/problems/add-two-numbers': typeof ProblemsAddTwoNumbersRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/browser-history': typeof ProblemsBrowserHistoryRoute
  '/problems/container-water': typeof ProblemsContainerWaterRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/fizz-buzz': typeof ProblemsFizzBuzzRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/fruit-into-baskets': typeof ProblemsFruitIntoBasketsRoute
  '/problems/longest-common-prefix': typeof ProblemsLongestCommonPrefixRoute
  '/problems/lru-cache': typeof ProblemsLruCacheRoute
  '/problems/magic-dictionary': typeof ProblemsMagicDictionaryRoute
  '/problems/merge-sorted-array': typeof ProblemsMergeSortedArrayRoute
  '/problems/ordered-stream': typeof ProblemsOrderedStreamRoute
  '/problems/randomized-set': typeof ProblemsRandomizedSetRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/rotting-oranges': typeof ProblemsRottingOrangesRoute
  '/problems/shortest-path-binary-matrix': typeof ProblemsShortestPathBinaryMatrixRoute
  '/problems/single-element-sorted': typeof ProblemsSingleElementSortedRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/top-k-frequent-words': typeof ProblemsTopKFrequentWordsRoute
  '/problems/underground-system': typeof ProblemsUndergroundSystemRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
  '/viz/$id': typeof VizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/problems/$slug': typeof AdminProblemsSlugRoute
  '/admin/problems/new': typeof AdminProblemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problems'
    | '/create'
    | '/gallery'
    | '/problem-list'
    | '/p/$slug'
    | '/problems/add-binary'
    | '/problems/add-two-numbers'
    | '/problems/basic-calculator-ii'
    | '/problems/browser-history'
    | '/problems/container-water'
    | '/problems/decode-string'
    | '/problems/fizz-buzz'
    | '/problems/flatten-multilevel-list'
    | '/problems/fruit-into-baskets'
    | '/problems/longest-common-prefix'
    | '/problems/lru-cache'
    | '/problems/magic-dictionary'
    | '/problems/merge-sorted-array'
    | '/problems/ordered-stream'
    | '/problems/randomized-set'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/rotting-oranges'
    | '/problems/shortest-path-binary-matrix'
    | '/problems/single-element-sorted'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/top-k-frequent-words'
    | '/problems/underground-system'
    | '/problems/validate-bst'
    | '/viz/$id'
    | '/admin'
    | '/admin/problems/$slug'
    | '/admin/problems/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problems'
    | '/create'
    | '/gallery'
    | '/problem-list'
    | '/p/$slug'
    | '/problems/add-binary'
    | '/problems/add-two-numbers'
    | '/problems/basic-calculator-ii'
    | '/problems/browser-history'
    | '/problems/container-water'
    | '/problems/decode-string'
    | '/problems/fizz-buzz'
    | '/problems/flatten-multilevel-list'
    | '/problems/fruit-into-baskets'
    | '/problems/longest-common-prefix'
    | '/problems/lru-cache'
    | '/problems/magic-dictionary'
    | '/problems/merge-sorted-array'
    | '/problems/ordered-stream'
    | '/problems/randomized-set'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/rotting-oranges'
    | '/problems/shortest-path-binary-matrix'
    | '/problems/single-element-sorted'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/top-k-frequent-words'
    | '/problems/underground-system'
    | '/problems/validate-bst'
    | '/viz/$id'
    | '/admin'
    | '/admin/problems/$slug'
    | '/admin/problems/new'
  id:
    | '__root__'
    | '/'
    | '/problems'
    | '/create'
    | '/gallery'
    | '/problem-list'
    | '/p/$slug'
    | '/problems/add-binary'
    | '/problems/add-two-numbers'
    | '/problems/basic-calculator-ii'
    | '/problems/browser-history'
    | '/problems/container-water'
    | '/problems/decode-string'
    | '/problems/fizz-buzz'
    | '/problems/flatten-multilevel-list'
    | '/problems/fruit-into-baskets'
    | '/problems/longest-common-prefix'
    | '/problems/lru-cache'
    | '/problems/magic-dictionary'
    | '/problems/merge-sorted-array'
    | '/problems/ordered-stream'
    | '/problems/randomized-set'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/rotting-oranges'
    | '/problems/shortest-path-binary-matrix'
    | '/problems/single-element-sorted'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/top-k-frequent-words'
    | '/problems/underground-system'
    | '/problems/validate-bst'
    | '/viz/$id'
    | '/admin/'
    | '/admin/problems/$slug'
    | '/admin/problems/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsRouteRoute: typeof ProblemsRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  GalleryRoute: typeof GalleryRoute
  ProblemListRoute: typeof ProblemListRoute
  PSlugRoute: typeof PSlugRoute
  VizIdRoute: typeof VizIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProblemsSlugRoute: typeof AdminProblemsSlugRoute
  AdminProblemsNewRoute: typeof AdminProblemsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/problem-list': {
      id: '/problem-list'
      path: '/problem-list'
      fullPath: '/problem-list'
      preLoaderRoute: typeof ProblemListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viz/$id': {
      id: '/viz/$id'
      path: '/viz/$id'
      fullPath: '/viz/$id'
      preLoaderRoute: typeof VizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/validate-bst': {
      id: '/problems/validate-bst'
      path: '/validate-bst'
      fullPath: '/problems/validate-bst'
      preLoaderRoute: typeof ProblemsValidateBstRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/underground-system': {
      id: '/problems/underground-system'
      path: '/underground-system'
      fullPath: '/problems/underground-system'
      preLoaderRoute: typeof ProblemsUndergroundSystemRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/top-k-frequent-words': {
      id: '/problems/top-k-frequent-words'
      path: '/top-k-frequent-words'
      fullPath: '/problems/top-k-frequent-words'
      preLoaderRoute: typeof ProblemsTopKFrequentWordsRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/three-sum': {
      id: '/problems/three-sum'
      path: '/three-sum'
      fullPath: '/problems/three-sum'
      preLoaderRoute: typeof ProblemsThreeSumRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/subarray-sum-k': {
      id: '/problems/subarray-sum-k'
      path: '/subarray-sum-k'
      fullPath: '/problems/subarray-sum-k'
      preLoaderRoute: typeof ProblemsSubarraySumKRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/single-element-sorted': {
      id: '/problems/single-element-sorted'
      path: '/single-element-sorted'
      fullPath: '/problems/single-element-sorted'
      preLoaderRoute: typeof ProblemsSingleElementSortedRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/shortest-path-binary-matrix': {
      id: '/problems/shortest-path-binary-matrix'
      path: '/shortest-path-binary-matrix'
      fullPath: '/problems/shortest-path-binary-matrix'
      preLoaderRoute: typeof ProblemsShortestPathBinaryMatrixRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/rotting-oranges': {
      id: '/problems/rotting-oranges'
      path: '/rotting-oranges'
      fullPath: '/problems/rotting-oranges'
      preLoaderRoute: typeof ProblemsRottingOrangesRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/rotate-image': {
      id: '/problems/rotate-image'
      path: '/rotate-image'
      fullPath: '/problems/rotate-image'
      preLoaderRoute: typeof ProblemsRotateImageRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/reverse-integer': {
      id: '/problems/reverse-integer'
      path: '/reverse-integer'
      fullPath: '/problems/reverse-integer'
      preLoaderRoute: typeof ProblemsReverseIntegerRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/remove-duplicates-ii': {
      id: '/problems/remove-duplicates-ii'
      path: '/remove-duplicates-ii'
      fullPath: '/problems/remove-duplicates-ii'
      preLoaderRoute: typeof ProblemsRemoveDuplicatesIiRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/randomized-set': {
      id: '/problems/randomized-set'
      path: '/randomized-set'
      fullPath: '/problems/randomized-set'
      preLoaderRoute: typeof ProblemsRandomizedSetRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/ordered-stream': {
      id: '/problems/ordered-stream'
      path: '/ordered-stream'
      fullPath: '/problems/ordered-stream'
      preLoaderRoute: typeof ProblemsOrderedStreamRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/merge-sorted-array': {
      id: '/problems/merge-sorted-array'
      path: '/merge-sorted-array'
      fullPath: '/problems/merge-sorted-array'
      preLoaderRoute: typeof ProblemsMergeSortedArrayRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/magic-dictionary': {
      id: '/problems/magic-dictionary'
      path: '/magic-dictionary'
      fullPath: '/problems/magic-dictionary'
      preLoaderRoute: typeof ProblemsMagicDictionaryRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/lru-cache': {
      id: '/problems/lru-cache'
      path: '/lru-cache'
      fullPath: '/problems/lru-cache'
      preLoaderRoute: typeof ProblemsLruCacheRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/longest-common-prefix': {
      id: '/problems/longest-common-prefix'
      path: '/longest-common-prefix'
      fullPath: '/problems/longest-common-prefix'
      preLoaderRoute: typeof ProblemsLongestCommonPrefixRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/fruit-into-baskets': {
      id: '/problems/fruit-into-baskets'
      path: '/fruit-into-baskets'
      fullPath: '/problems/fruit-into-baskets'
      preLoaderRoute: typeof ProblemsFruitIntoBasketsRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/flatten-multilevel-list': {
      id: '/problems/flatten-multilevel-list'
      path: '/flatten-multilevel-list'
      fullPath: '/problems/flatten-multilevel-list'
      preLoaderRoute: typeof ProblemsFlattenMultilevelListRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/fizz-buzz': {
      id: '/problems/fizz-buzz'
      path: '/fizz-buzz'
      fullPath: '/problems/fizz-buzz'
      preLoaderRoute: typeof ProblemsFizzBuzzRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/decode-string': {
      id: '/problems/decode-string'
      path: '/decode-string'
      fullPath: '/problems/decode-string'
      preLoaderRoute: typeof ProblemsDecodeStringRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/container-water': {
      id: '/problems/container-water'
      path: '/container-water'
      fullPath: '/problems/container-water'
      preLoaderRoute: typeof ProblemsContainerWaterRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/browser-history': {
      id: '/problems/browser-history'
      path: '/browser-history'
      fullPath: '/problems/browser-history'
      preLoaderRoute: typeof ProblemsBrowserHistoryRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/basic-calculator-ii': {
      id: '/problems/basic-calculator-ii'
      path: '/basic-calculator-ii'
      fullPath: '/problems/basic-calculator-ii'
      preLoaderRoute: typeof ProblemsBasicCalculatorIiRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/add-two-numbers': {
      id: '/problems/add-two-numbers'
      path: '/add-two-numbers'
      fullPath: '/problems/add-two-numbers'
      preLoaderRoute: typeof ProblemsAddTwoNumbersRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/problems/add-binary': {
      id: '/problems/add-binary'
      path: '/add-binary'
      fullPath: '/problems/add-binary'
      preLoaderRoute: typeof ProblemsAddBinaryRouteImport
      parentRoute: typeof ProblemsRouteRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems/new': {
      id: '/admin/problems/new'
      path: '/admin/problems/new'
      fullPath: '/admin/problems/new'
      preLoaderRoute: typeof AdminProblemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems/$slug': {
      id: '/admin/problems/$slug'
      path: '/admin/problems/$slug'
      fullPath: '/admin/problems/$slug'
      preLoaderRoute: typeof AdminProblemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProblemsRouteRouteChildren {
  ProblemsAddBinaryRoute: typeof ProblemsAddBinaryRoute
  ProblemsAddTwoNumbersRoute: typeof ProblemsAddTwoNumbersRoute
  ProblemsBasicCalculatorIiRoute: typeof ProblemsBasicCalculatorIiRoute
  ProblemsBrowserHistoryRoute: typeof ProblemsBrowserHistoryRoute
  ProblemsContainerWaterRoute: typeof ProblemsContainerWaterRoute
  ProblemsDecodeStringRoute: typeof ProblemsDecodeStringRoute
  ProblemsFizzBuzzRoute: typeof ProblemsFizzBuzzRoute
  ProblemsFlattenMultilevelListRoute: typeof ProblemsFlattenMultilevelListRoute
  ProblemsFruitIntoBasketsRoute: typeof ProblemsFruitIntoBasketsRoute
  ProblemsLongestCommonPrefixRoute: typeof ProblemsLongestCommonPrefixRoute
  ProblemsLruCacheRoute: typeof ProblemsLruCacheRoute
  ProblemsMagicDictionaryRoute: typeof ProblemsMagicDictionaryRoute
  ProblemsMergeSortedArrayRoute: typeof ProblemsMergeSortedArrayRoute
  ProblemsOrderedStreamRoute: typeof ProblemsOrderedStreamRoute
  ProblemsRandomizedSetRoute: typeof ProblemsRandomizedSetRoute
  ProblemsRemoveDuplicatesIiRoute: typeof ProblemsRemoveDuplicatesIiRoute
  ProblemsReverseIntegerRoute: typeof ProblemsReverseIntegerRoute
  ProblemsRotateImageRoute: typeof ProblemsRotateImageRoute
  ProblemsRottingOrangesRoute: typeof ProblemsRottingOrangesRoute
  ProblemsShortestPathBinaryMatrixRoute: typeof ProblemsShortestPathBinaryMatrixRoute
  ProblemsSingleElementSortedRoute: typeof ProblemsSingleElementSortedRoute
  ProblemsSubarraySumKRoute: typeof ProblemsSubarraySumKRoute
  ProblemsThreeSumRoute: typeof ProblemsThreeSumRoute
  ProblemsTopKFrequentWordsRoute: typeof ProblemsTopKFrequentWordsRoute
  ProblemsUndergroundSystemRoute: typeof ProblemsUndergroundSystemRoute
  ProblemsValidateBstRoute: typeof ProblemsValidateBstRoute
}

const ProblemsRouteRouteChildren: ProblemsRouteRouteChildren = {
  ProblemsAddBinaryRoute: ProblemsAddBinaryRoute,
  ProblemsAddTwoNumbersRoute: ProblemsAddTwoNumbersRoute,
  ProblemsBasicCalculatorIiRoute: ProblemsBasicCalculatorIiRoute,
  ProblemsBrowserHistoryRoute: ProblemsBrowserHistoryRoute,
  ProblemsContainerWaterRoute: ProblemsContainerWaterRoute,
  ProblemsDecodeStringRoute: ProblemsDecodeStringRoute,
  ProblemsFizzBuzzRoute: ProblemsFizzBuzzRoute,
  ProblemsFlattenMultilevelListRoute: ProblemsFlattenMultilevelListRoute,
  ProblemsFruitIntoBasketsRoute: ProblemsFruitIntoBasketsRoute,
  ProblemsLongestCommonPrefixRoute: ProblemsLongestCommonPrefixRoute,
  ProblemsLruCacheRoute: ProblemsLruCacheRoute,
  ProblemsMagicDictionaryRoute: ProblemsMagicDictionaryRoute,
  ProblemsMergeSortedArrayRoute: ProblemsMergeSortedArrayRoute,
  ProblemsOrderedStreamRoute: ProblemsOrderedStreamRoute,
  ProblemsRandomizedSetRoute: ProblemsRandomizedSetRoute,
  ProblemsRemoveDuplicatesIiRoute: ProblemsRemoveDuplicatesIiRoute,
  ProblemsReverseIntegerRoute: ProblemsReverseIntegerRoute,
  ProblemsRotateImageRoute: ProblemsRotateImageRoute,
  ProblemsRottingOrangesRoute: ProblemsRottingOrangesRoute,
  ProblemsShortestPathBinaryMatrixRoute: ProblemsShortestPathBinaryMatrixRoute,
  ProblemsSingleElementSortedRoute: ProblemsSingleElementSortedRoute,
  ProblemsSubarraySumKRoute: ProblemsSubarraySumKRoute,
  ProblemsThreeSumRoute: ProblemsThreeSumRoute,
  ProblemsTopKFrequentWordsRoute: ProblemsTopKFrequentWordsRoute,
  ProblemsUndergroundSystemRoute: ProblemsUndergroundSystemRoute,
  ProblemsValidateBstRoute: ProblemsValidateBstRoute,
}

const ProblemsRouteRouteWithChildren = ProblemsRouteRoute._addFileChildren(
  ProblemsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsRouteRoute: ProblemsRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  GalleryRoute: GalleryRoute,
  ProblemListRoute: ProblemListRoute,
  PSlugRoute: PSlugRoute,
  VizIdRoute: VizIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProblemsSlugRoute: AdminProblemsSlugRoute,
  AdminProblemsNewRoute: AdminProblemsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
