/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsValidateBstRouteImport } from './routes/problems/validate-bst'
import { Route as ProblemsThreeSumRouteImport } from './routes/problems/three-sum'
import { Route as ProblemsSubarraySumKRouteImport } from './routes/problems/subarray-sum-k'
import { Route as ProblemsRotateImageRouteImport } from './routes/problems/rotate-image'
import { Route as ProblemsReverseIntegerRouteImport } from './routes/problems/reverse-integer'
import { Route as ProblemsRemoveDuplicatesIiRouteImport } from './routes/problems/remove-duplicates-ii'
import { Route as ProblemsFlattenMultilevelListRouteImport } from './routes/problems/flatten-multilevel-list'
import { Route as ProblemsDecodeStringRouteImport } from './routes/problems/decode-string'
import { Route as ProblemsBasicCalculatorIiRouteImport } from './routes/problems/basic-calculator-ii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsValidateBstRoute = ProblemsValidateBstRouteImport.update({
  id: '/problems/validate-bst',
  path: '/problems/validate-bst',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsThreeSumRoute = ProblemsThreeSumRouteImport.update({
  id: '/problems/three-sum',
  path: '/problems/three-sum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSubarraySumKRoute = ProblemsSubarraySumKRouteImport.update({
  id: '/problems/subarray-sum-k',
  path: '/problems/subarray-sum-k',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRotateImageRoute = ProblemsRotateImageRouteImport.update({
  id: '/problems/rotate-image',
  path: '/problems/rotate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsReverseIntegerRoute = ProblemsReverseIntegerRouteImport.update({
  id: '/problems/reverse-integer',
  path: '/problems/reverse-integer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRemoveDuplicatesIiRoute =
  ProblemsRemoveDuplicatesIiRouteImport.update({
    id: '/problems/remove-duplicates-ii',
    path: '/problems/remove-duplicates-ii',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProblemsFlattenMultilevelListRoute =
  ProblemsFlattenMultilevelListRouteImport.update({
    id: '/problems/flatten-multilevel-list',
    path: '/problems/flatten-multilevel-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProblemsDecodeStringRoute = ProblemsDecodeStringRouteImport.update({
  id: '/problems/decode-string',
  path: '/problems/decode-string',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsBasicCalculatorIiRoute =
  ProblemsBasicCalculatorIiRouteImport.update({
    id: '/problems/basic-calculator-ii',
    path: '/problems/basic-calculator-ii',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problems/basic-calculator-ii': typeof ProblemsBasicCalculatorIiRoute
  '/problems/decode-string': typeof ProblemsDecodeStringRoute
  '/problems/flatten-multilevel-list': typeof ProblemsFlattenMultilevelListRoute
  '/problems/remove-duplicates-ii': typeof ProblemsRemoveDuplicatesIiRoute
  '/problems/reverse-integer': typeof ProblemsReverseIntegerRoute
  '/problems/rotate-image': typeof ProblemsRotateImageRoute
  '/problems/subarray-sum-k': typeof ProblemsSubarraySumKRoute
  '/problems/three-sum': typeof ProblemsThreeSumRoute
  '/problems/validate-bst': typeof ProblemsValidateBstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/problems/basic-calculator-ii'
    | '/problems/decode-string'
    | '/problems/flatten-multilevel-list'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/validate-bst'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/problems/basic-calculator-ii'
    | '/problems/decode-string'
    | '/problems/flatten-multilevel-list'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/validate-bst'
  id:
    | '__root__'
    | '/'
    | '/problems/basic-calculator-ii'
    | '/problems/decode-string'
    | '/problems/flatten-multilevel-list'
    | '/problems/remove-duplicates-ii'
    | '/problems/reverse-integer'
    | '/problems/rotate-image'
    | '/problems/subarray-sum-k'
    | '/problems/three-sum'
    | '/problems/validate-bst'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemsBasicCalculatorIiRoute: typeof ProblemsBasicCalculatorIiRoute
  ProblemsDecodeStringRoute: typeof ProblemsDecodeStringRoute
  ProblemsFlattenMultilevelListRoute: typeof ProblemsFlattenMultilevelListRoute
  ProblemsRemoveDuplicatesIiRoute: typeof ProblemsRemoveDuplicatesIiRoute
  ProblemsReverseIntegerRoute: typeof ProblemsReverseIntegerRoute
  ProblemsRotateImageRoute: typeof ProblemsRotateImageRoute
  ProblemsSubarraySumKRoute: typeof ProblemsSubarraySumKRoute
  ProblemsThreeSumRoute: typeof ProblemsThreeSumRoute
  ProblemsValidateBstRoute: typeof ProblemsValidateBstRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/validate-bst': {
      id: '/problems/validate-bst'
      path: '/problems/validate-bst'
      fullPath: '/problems/validate-bst'
      preLoaderRoute: typeof ProblemsValidateBstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/three-sum': {
      id: '/problems/three-sum'
      path: '/problems/three-sum'
      fullPath: '/problems/three-sum'
      preLoaderRoute: typeof ProblemsThreeSumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/subarray-sum-k': {
      id: '/problems/subarray-sum-k'
      path: '/problems/subarray-sum-k'
      fullPath: '/problems/subarray-sum-k'
      preLoaderRoute: typeof ProblemsSubarraySumKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/rotate-image': {
      id: '/problems/rotate-image'
      path: '/problems/rotate-image'
      fullPath: '/problems/rotate-image'
      preLoaderRoute: typeof ProblemsRotateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/reverse-integer': {
      id: '/problems/reverse-integer'
      path: '/problems/reverse-integer'
      fullPath: '/problems/reverse-integer'
      preLoaderRoute: typeof ProblemsReverseIntegerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/remove-duplicates-ii': {
      id: '/problems/remove-duplicates-ii'
      path: '/problems/remove-duplicates-ii'
      fullPath: '/problems/remove-duplicates-ii'
      preLoaderRoute: typeof ProblemsRemoveDuplicatesIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/flatten-multilevel-list': {
      id: '/problems/flatten-multilevel-list'
      path: '/problems/flatten-multilevel-list'
      fullPath: '/problems/flatten-multilevel-list'
      preLoaderRoute: typeof ProblemsFlattenMultilevelListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/decode-string': {
      id: '/problems/decode-string'
      path: '/problems/decode-string'
      fullPath: '/problems/decode-string'
      preLoaderRoute: typeof ProblemsDecodeStringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/basic-calculator-ii': {
      id: '/problems/basic-calculator-ii'
      path: '/problems/basic-calculator-ii'
      fullPath: '/problems/basic-calculator-ii'
      preLoaderRoute: typeof ProblemsBasicCalculatorIiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemsBasicCalculatorIiRoute: ProblemsBasicCalculatorIiRoute,
  ProblemsDecodeStringRoute: ProblemsDecodeStringRoute,
  ProblemsFlattenMultilevelListRoute: ProblemsFlattenMultilevelListRoute,
  ProblemsRemoveDuplicatesIiRoute: ProblemsRemoveDuplicatesIiRoute,
  ProblemsReverseIntegerRoute: ProblemsReverseIntegerRoute,
  ProblemsRotateImageRoute: ProblemsRotateImageRoute,
  ProblemsSubarraySumKRoute: ProblemsSubarraySumKRoute,
  ProblemsThreeSumRoute: ProblemsThreeSumRoute,
  ProblemsValidateBstRoute: ProblemsValidateBstRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
